### ISSUE TITLE
Could you please upgrade to the latest?

### ISSUE THREAD

**Issue by cyrilfr** [layershift/odoo-centos#2]
Could you please upgrade to the latest? I get an "Access denied" error.

**Comment by sebastian-pusta1** [comment]
Hello,
We're already working on upgrading odoo to the latest version. There are a few issues with this so it will take a bit more time.
Please stand by for updates.

**Comment by cyrilfr** [comment]
I got a JPS from Jelastic to install the v12:

```
type: install
id: odoo-ce
name: Odoo Community Edition
homepage: http:///www.odoo.com/
baseUrl: https://raw.githubusercontent.com/jelastic-jps/odoo/master
logo: /images/odoo-logo.png
categories:
  - apps/cms
  - apps/popular
  - apps/content-management
description: 
  text: Odoo is an all-in-one business management software to run a company (ERP, CMS, CRM application, e-Commerce backend, etc). 
    With 10.000+ apps in, Odoo covers all your business needs in a one-stop solution and provides top notch usability that scales across all apps. 
  short: Odoo is an all-in-one business software (ERP, CMS, CRM application, e-Commerce backend, etc).
globals:
  db_user: odoo-${fn.random(1000)}
  db_pswd: ${fn.password}
  master_pswd: ${fn.password}
ssl: true
skipNodeEmails: true
nodes:
- nodeType: nginx
  displayName: Balancer
  cloudlets: 16
  nodeGroup: bl
- image: odoo:12.0
  displayName: App Server
  cloudlets: 16
  nodeGroup: cp
  links: sqldb:db
  env:
    JELASTIC_EXPOSE: 8069
- image: postgres:10
  cloudlets: 16
  nodeGroup: sqldb
  displayName: Postgres DB
  env:
    POSTGRES_USER: ${globals.db_user}
    POSTGRES_PASSWORD: ${globals.db_pswd}
    POSTGRES_DB: postgres
onInstall:
  - if ('${env.protocol}' == 'https'): 
      cmd[bl]: |-
        sed -i ':a;$!{N;ba};s/\(location \/ {\)/\1\n\n\t\t\t\t\t\tif ($http_x_forwarded_proto = http) {\n\t\t\t\t\t\t\t\treturn 302 https:\/\/$host$request_uri;\n\t\t\t\t\t\t\t\terror_page  500 502 503 504 = @rescue;\n\t\t\t\t\t\t}\n/1' /etc/nginx/nginx-jelastic.conf
        service nginx restart
      user: root
  - cmd[cp]: |-
      sudo sed -i s/"; admin_passwd.*"/"admin_passwd = ${globals.master_pswd}"/g /etc/odoo/odoo.conf
      echo "db_host = $DB_HOST" >> /etc/odoo/odoo.conf
      echo "db_port = $DB_PORT" >> /etc/odoo/odoo.conf
      echo "db_password = $DB_POSTGRES_PASSWORD" >> /etc/odoo/odoo.conf
      echo "db_user = $DB_POSTGRES_USER" >> /etc/odoo/odoo.conf
      echo "proxy_mode = True" >> /etc/odoo/odoo.conf
      echo "workers = $(($(grep -c ^processor /proc/cpuinfo)*2))" >> /etc/odoo/odoo.conf
      echo "max_cron_threads = 1" >> /etc/odoo/odoo.conf
      /etc/init.d/odoo restart
success: |-
  Please open [${env.url}](${env.url}) and complete the installation. 
    
  **Master Password:** ${globals.master_pswd} 
```
